//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ElecDocServices.EforconServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://www.eforcon.com/WebService")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback mFacturaXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback mNotaCreditoXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback mNotaDebitoXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback mFacturaCopiaXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback mNotaCreditoCopiaXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback mNotaDebitoCopiaXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback mAnularFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback mAnularNCOperationCompleted;
        
        private System.Threading.SendOrPostCallback mAnularNDOperationCompleted;
        
        private System.Threading.SendOrPostCallback mObtieneInfoFACEOperationCompleted;
        
        private System.Threading.SendOrPostCallback mObtieneInfoNCEOperationCompleted;
        
        private System.Threading.SendOrPostCallback mObtieneInfoNDEOperationCompleted;
        
        private System.Threading.SendOrPostCallback mCrearEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback mFacturaXML2OperationCompleted;
        
        private System.Threading.SendOrPostCallback mCatalogoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mFacturaXML3OperationCompleted;
        
        private System.Threading.SendOrPostCallback mNotaDebitoCAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback mNotaCreditoCAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback mReciboCajaOperationCompleted;
        
        private System.Threading.SendOrPostCallback mFacturaCAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback mFacturaXMLCorreo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback mObtieneInfoCorrelativoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mConsultarFaceRegimenFelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ElecDocServices.Properties.Settings.Default.ElecDocServices_EforconServices_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mLoginCompletedEventHandler mLoginCompleted;
        
        /// <remarks/>
        public event mFacturaXMLCompletedEventHandler mFacturaXMLCompleted;
        
        /// <remarks/>
        public event mNotaCreditoXmlCompletedEventHandler mNotaCreditoXmlCompleted;
        
        /// <remarks/>
        public event mNotaDebitoXmlCompletedEventHandler mNotaDebitoXmlCompleted;
        
        /// <remarks/>
        public event mFacturaCopiaXMLCompletedEventHandler mFacturaCopiaXMLCompleted;
        
        /// <remarks/>
        public event mNotaCreditoCopiaXmlCompletedEventHandler mNotaCreditoCopiaXmlCompleted;
        
        /// <remarks/>
        public event mNotaDebitoCopiaXmlCompletedEventHandler mNotaDebitoCopiaXmlCompleted;
        
        /// <remarks/>
        public event mAnularFacturaCompletedEventHandler mAnularFacturaCompleted;
        
        /// <remarks/>
        public event mAnularNCCompletedEventHandler mAnularNCCompleted;
        
        /// <remarks/>
        public event mAnularNDCompletedEventHandler mAnularNDCompleted;
        
        /// <remarks/>
        public event mObtieneInfoFACECompletedEventHandler mObtieneInfoFACECompleted;
        
        /// <remarks/>
        public event mObtieneInfoNCECompletedEventHandler mObtieneInfoNCECompleted;
        
        /// <remarks/>
        public event mObtieneInfoNDECompletedEventHandler mObtieneInfoNDECompleted;
        
        /// <remarks/>
        public event mCrearEmpresaCompletedEventHandler mCrearEmpresaCompleted;
        
        /// <remarks/>
        public event mFacturaXML2CompletedEventHandler mFacturaXML2Completed;
        
        /// <remarks/>
        public event mCatalogoCompletedEventHandler mCatalogoCompleted;
        
        /// <remarks/>
        public event mFacturaXML3CompletedEventHandler mFacturaXML3Completed;
        
        /// <remarks/>
        public event mNotaDebitoCAECompletedEventHandler mNotaDebitoCAECompleted;
        
        /// <remarks/>
        public event mNotaCreditoCAECompletedEventHandler mNotaCreditoCAECompleted;
        
        /// <remarks/>
        public event mReciboCajaCompletedEventHandler mReciboCajaCompleted;
        
        /// <remarks/>
        public event mFacturaCAECompletedEventHandler mFacturaCAECompleted;
        
        /// <remarks/>
        public event mFacturaXMLCorreo2CompletedEventHandler mFacturaXMLCorreo2Completed;
        
        /// <remarks/>
        public event mObtieneInfoCorrelativoCompletedEventHandler mObtieneInfoCorrelativoCompleted;
        
        /// <remarks/>
        public event mConsultarFaceRegimenFelCompletedEventHandler mConsultarFaceRegimenFelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mLogin", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mLogin(string oIdUsuario, string oIdClave) {
            object[] results = this.Invoke("mLogin", new object[] {
                        oIdUsuario,
                        oIdClave});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mLoginAsync(string oIdUsuario, string oIdClave) {
            this.mLoginAsync(oIdUsuario, oIdClave, null);
        }
        
        /// <remarks/>
        public void mLoginAsync(string oIdUsuario, string oIdClave, object userState) {
            if ((this.mLoginOperationCompleted == null)) {
                this.mLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmLoginOperationCompleted);
            }
            this.InvokeAsync("mLogin", new object[] {
                        oIdUsuario,
                        oIdClave}, this.mLoginOperationCompleted, userState);
        }
        
        private void OnmLoginOperationCompleted(object arg) {
            if ((this.mLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mLoginCompleted(this, new mLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mFacturaXML", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mFacturaXML(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mFacturaXML", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mFacturaXMLAsync(string user, string clave, string pXMLFactura) {
            this.mFacturaXMLAsync(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mFacturaXMLAsync(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mFacturaXMLOperationCompleted == null)) {
                this.mFacturaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmFacturaXMLOperationCompleted);
            }
            this.InvokeAsync("mFacturaXML", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mFacturaXMLOperationCompleted, userState);
        }
        
        private void OnmFacturaXMLOperationCompleted(object arg) {
            if ((this.mFacturaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mFacturaXMLCompleted(this, new mFacturaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mNotaCreditoXml", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mNotaCreditoXml(string user, string clave, string pXMLCredito) {
            object[] results = this.Invoke("mNotaCreditoXml", new object[] {
                        user,
                        clave,
                        pXMLCredito});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mNotaCreditoXmlAsync(string user, string clave, string pXMLCredito) {
            this.mNotaCreditoXmlAsync(user, clave, pXMLCredito, null);
        }
        
        /// <remarks/>
        public void mNotaCreditoXmlAsync(string user, string clave, string pXMLCredito, object userState) {
            if ((this.mNotaCreditoXmlOperationCompleted == null)) {
                this.mNotaCreditoXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmNotaCreditoXmlOperationCompleted);
            }
            this.InvokeAsync("mNotaCreditoXml", new object[] {
                        user,
                        clave,
                        pXMLCredito}, this.mNotaCreditoXmlOperationCompleted, userState);
        }
        
        private void OnmNotaCreditoXmlOperationCompleted(object arg) {
            if ((this.mNotaCreditoXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mNotaCreditoXmlCompleted(this, new mNotaCreditoXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mNotaDebitoXml", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mNotaDebitoXml(string user, string clave, string pXMLDebito) {
            object[] results = this.Invoke("mNotaDebitoXml", new object[] {
                        user,
                        clave,
                        pXMLDebito});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mNotaDebitoXmlAsync(string user, string clave, string pXMLDebito) {
            this.mNotaDebitoXmlAsync(user, clave, pXMLDebito, null);
        }
        
        /// <remarks/>
        public void mNotaDebitoXmlAsync(string user, string clave, string pXMLDebito, object userState) {
            if ((this.mNotaDebitoXmlOperationCompleted == null)) {
                this.mNotaDebitoXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmNotaDebitoXmlOperationCompleted);
            }
            this.InvokeAsync("mNotaDebitoXml", new object[] {
                        user,
                        clave,
                        pXMLDebito}, this.mNotaDebitoXmlOperationCompleted, userState);
        }
        
        private void OnmNotaDebitoXmlOperationCompleted(object arg) {
            if ((this.mNotaDebitoXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mNotaDebitoXmlCompleted(this, new mNotaDebitoXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mFacturaCopiaXML", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mFacturaCopiaXML(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mFacturaCopiaXML", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mFacturaCopiaXMLAsync(string user, string clave, string pXMLFactura) {
            this.mFacturaCopiaXMLAsync(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mFacturaCopiaXMLAsync(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mFacturaCopiaXMLOperationCompleted == null)) {
                this.mFacturaCopiaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmFacturaCopiaXMLOperationCompleted);
            }
            this.InvokeAsync("mFacturaCopiaXML", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mFacturaCopiaXMLOperationCompleted, userState);
        }
        
        private void OnmFacturaCopiaXMLOperationCompleted(object arg) {
            if ((this.mFacturaCopiaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mFacturaCopiaXMLCompleted(this, new mFacturaCopiaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mNotaCreditoCopiaXml", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mNotaCreditoCopiaXml(string user, string clave, string pXMLCredito) {
            object[] results = this.Invoke("mNotaCreditoCopiaXml", new object[] {
                        user,
                        clave,
                        pXMLCredito});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mNotaCreditoCopiaXmlAsync(string user, string clave, string pXMLCredito) {
            this.mNotaCreditoCopiaXmlAsync(user, clave, pXMLCredito, null);
        }
        
        /// <remarks/>
        public void mNotaCreditoCopiaXmlAsync(string user, string clave, string pXMLCredito, object userState) {
            if ((this.mNotaCreditoCopiaXmlOperationCompleted == null)) {
                this.mNotaCreditoCopiaXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmNotaCreditoCopiaXmlOperationCompleted);
            }
            this.InvokeAsync("mNotaCreditoCopiaXml", new object[] {
                        user,
                        clave,
                        pXMLCredito}, this.mNotaCreditoCopiaXmlOperationCompleted, userState);
        }
        
        private void OnmNotaCreditoCopiaXmlOperationCompleted(object arg) {
            if ((this.mNotaCreditoCopiaXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mNotaCreditoCopiaXmlCompleted(this, new mNotaCreditoCopiaXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mNotaDebitoCopiaXml", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mNotaDebitoCopiaXml(string user, string clave, string pXMLDebito) {
            object[] results = this.Invoke("mNotaDebitoCopiaXml", new object[] {
                        user,
                        clave,
                        pXMLDebito});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mNotaDebitoCopiaXmlAsync(string user, string clave, string pXMLDebito) {
            this.mNotaDebitoCopiaXmlAsync(user, clave, pXMLDebito, null);
        }
        
        /// <remarks/>
        public void mNotaDebitoCopiaXmlAsync(string user, string clave, string pXMLDebito, object userState) {
            if ((this.mNotaDebitoCopiaXmlOperationCompleted == null)) {
                this.mNotaDebitoCopiaXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmNotaDebitoCopiaXmlOperationCompleted);
            }
            this.InvokeAsync("mNotaDebitoCopiaXml", new object[] {
                        user,
                        clave,
                        pXMLDebito}, this.mNotaDebitoCopiaXmlOperationCompleted, userState);
        }
        
        private void OnmNotaDebitoCopiaXmlOperationCompleted(object arg) {
            if ((this.mNotaDebitoCopiaXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mNotaDebitoCopiaXmlCompleted(this, new mNotaDebitoCopiaXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mAnularFactura", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mAnularFactura(string user, string clave, string resolucion, string serie, int noFactura, int anio, string razon) {
            object[] results = this.Invoke("mAnularFactura", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noFactura,
                        anio,
                        razon});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mAnularFacturaAsync(string user, string clave, string resolucion, string serie, int noFactura, int anio, string razon) {
            this.mAnularFacturaAsync(user, clave, resolucion, serie, noFactura, anio, razon, null);
        }
        
        /// <remarks/>
        public void mAnularFacturaAsync(string user, string clave, string resolucion, string serie, int noFactura, int anio, string razon, object userState) {
            if ((this.mAnularFacturaOperationCompleted == null)) {
                this.mAnularFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmAnularFacturaOperationCompleted);
            }
            this.InvokeAsync("mAnularFactura", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noFactura,
                        anio,
                        razon}, this.mAnularFacturaOperationCompleted, userState);
        }
        
        private void OnmAnularFacturaOperationCompleted(object arg) {
            if ((this.mAnularFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mAnularFacturaCompleted(this, new mAnularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mAnularNC", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mAnularNC(string user, string clave, string resolucion, string serie, int noNC, int anio, string razon) {
            object[] results = this.Invoke("mAnularNC", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noNC,
                        anio,
                        razon});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mAnularNCAsync(string user, string clave, string resolucion, string serie, int noNC, int anio, string razon) {
            this.mAnularNCAsync(user, clave, resolucion, serie, noNC, anio, razon, null);
        }
        
        /// <remarks/>
        public void mAnularNCAsync(string user, string clave, string resolucion, string serie, int noNC, int anio, string razon, object userState) {
            if ((this.mAnularNCOperationCompleted == null)) {
                this.mAnularNCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmAnularNCOperationCompleted);
            }
            this.InvokeAsync("mAnularNC", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noNC,
                        anio,
                        razon}, this.mAnularNCOperationCompleted, userState);
        }
        
        private void OnmAnularNCOperationCompleted(object arg) {
            if ((this.mAnularNCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mAnularNCCompleted(this, new mAnularNCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mAnularND", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mAnularND(string user, string clave, string resolucion, string serie, int noND, int anio, string razon) {
            object[] results = this.Invoke("mAnularND", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noND,
                        anio,
                        razon});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mAnularNDAsync(string user, string clave, string resolucion, string serie, int noND, int anio, string razon) {
            this.mAnularNDAsync(user, clave, resolucion, serie, noND, anio, razon, null);
        }
        
        /// <remarks/>
        public void mAnularNDAsync(string user, string clave, string resolucion, string serie, int noND, int anio, string razon, object userState) {
            if ((this.mAnularNDOperationCompleted == null)) {
                this.mAnularNDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmAnularNDOperationCompleted);
            }
            this.InvokeAsync("mAnularND", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noND,
                        anio,
                        razon}, this.mAnularNDOperationCompleted, userState);
        }
        
        private void OnmAnularNDOperationCompleted(object arg) {
            if ((this.mAnularNDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mAnularNDCompleted(this, new mAnularNDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mObtieneInfoFACE", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mObtieneInfoFACE(string user, string clave, string resolucion, string serie, int noFact, int anio) {
            object[] results = this.Invoke("mObtieneInfoFACE", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noFact,
                        anio});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mObtieneInfoFACEAsync(string user, string clave, string resolucion, string serie, int noFact, int anio) {
            this.mObtieneInfoFACEAsync(user, clave, resolucion, serie, noFact, anio, null);
        }
        
        /// <remarks/>
        public void mObtieneInfoFACEAsync(string user, string clave, string resolucion, string serie, int noFact, int anio, object userState) {
            if ((this.mObtieneInfoFACEOperationCompleted == null)) {
                this.mObtieneInfoFACEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmObtieneInfoFACEOperationCompleted);
            }
            this.InvokeAsync("mObtieneInfoFACE", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noFact,
                        anio}, this.mObtieneInfoFACEOperationCompleted, userState);
        }
        
        private void OnmObtieneInfoFACEOperationCompleted(object arg) {
            if ((this.mObtieneInfoFACECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mObtieneInfoFACECompleted(this, new mObtieneInfoFACECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mObtieneInfoNCE", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mObtieneInfoNCE(string user, string clave, string resolucion, string serie, int noNC, int anio) {
            object[] results = this.Invoke("mObtieneInfoNCE", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noNC,
                        anio});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mObtieneInfoNCEAsync(string user, string clave, string resolucion, string serie, int noNC, int anio) {
            this.mObtieneInfoNCEAsync(user, clave, resolucion, serie, noNC, anio, null);
        }
        
        /// <remarks/>
        public void mObtieneInfoNCEAsync(string user, string clave, string resolucion, string serie, int noNC, int anio, object userState) {
            if ((this.mObtieneInfoNCEOperationCompleted == null)) {
                this.mObtieneInfoNCEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmObtieneInfoNCEOperationCompleted);
            }
            this.InvokeAsync("mObtieneInfoNCE", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noNC,
                        anio}, this.mObtieneInfoNCEOperationCompleted, userState);
        }
        
        private void OnmObtieneInfoNCEOperationCompleted(object arg) {
            if ((this.mObtieneInfoNCECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mObtieneInfoNCECompleted(this, new mObtieneInfoNCECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mObtieneInfoNDE", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mObtieneInfoNDE(string user, string clave, string resolucion, string serie, int noND, int anio) {
            object[] results = this.Invoke("mObtieneInfoNDE", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noND,
                        anio});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mObtieneInfoNDEAsync(string user, string clave, string resolucion, string serie, int noND, int anio) {
            this.mObtieneInfoNDEAsync(user, clave, resolucion, serie, noND, anio, null);
        }
        
        /// <remarks/>
        public void mObtieneInfoNDEAsync(string user, string clave, string resolucion, string serie, int noND, int anio, object userState) {
            if ((this.mObtieneInfoNDEOperationCompleted == null)) {
                this.mObtieneInfoNDEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmObtieneInfoNDEOperationCompleted);
            }
            this.InvokeAsync("mObtieneInfoNDE", new object[] {
                        user,
                        clave,
                        resolucion,
                        serie,
                        noND,
                        anio}, this.mObtieneInfoNDEOperationCompleted, userState);
        }
        
        private void OnmObtieneInfoNDEOperationCompleted(object arg) {
            if ((this.mObtieneInfoNDECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mObtieneInfoNDECompleted(this, new mObtieneInfoNDECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mCrearEmpresa", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mCrearEmpresa(string user, string clave, string TipoEmisor, string Descripcion, string RazonSocial, string NIT) {
            object[] results = this.Invoke("mCrearEmpresa", new object[] {
                        user,
                        clave,
                        TipoEmisor,
                        Descripcion,
                        RazonSocial,
                        NIT});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mCrearEmpresaAsync(string user, string clave, string TipoEmisor, string Descripcion, string RazonSocial, string NIT) {
            this.mCrearEmpresaAsync(user, clave, TipoEmisor, Descripcion, RazonSocial, NIT, null);
        }
        
        /// <remarks/>
        public void mCrearEmpresaAsync(string user, string clave, string TipoEmisor, string Descripcion, string RazonSocial, string NIT, object userState) {
            if ((this.mCrearEmpresaOperationCompleted == null)) {
                this.mCrearEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmCrearEmpresaOperationCompleted);
            }
            this.InvokeAsync("mCrearEmpresa", new object[] {
                        user,
                        clave,
                        TipoEmisor,
                        Descripcion,
                        RazonSocial,
                        NIT}, this.mCrearEmpresaOperationCompleted, userState);
        }
        
        private void OnmCrearEmpresaOperationCompleted(object arg) {
            if ((this.mCrearEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mCrearEmpresaCompleted(this, new mCrearEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mFacturaXML2", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mFacturaXML2(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mFacturaXML2", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mFacturaXML2Async(string user, string clave, string pXMLFactura) {
            this.mFacturaXML2Async(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mFacturaXML2Async(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mFacturaXML2OperationCompleted == null)) {
                this.mFacturaXML2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnmFacturaXML2OperationCompleted);
            }
            this.InvokeAsync("mFacturaXML2", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mFacturaXML2OperationCompleted, userState);
        }
        
        private void OnmFacturaXML2OperationCompleted(object arg) {
            if ((this.mFacturaXML2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mFacturaXML2Completed(this, new mFacturaXML2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mCatalogo", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mCatalogo(string user, string clave, string codPro) {
            object[] results = this.Invoke("mCatalogo", new object[] {
                        user,
                        clave,
                        codPro});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mCatalogoAsync(string user, string clave, string codPro) {
            this.mCatalogoAsync(user, clave, codPro, null);
        }
        
        /// <remarks/>
        public void mCatalogoAsync(string user, string clave, string codPro, object userState) {
            if ((this.mCatalogoOperationCompleted == null)) {
                this.mCatalogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmCatalogoOperationCompleted);
            }
            this.InvokeAsync("mCatalogo", new object[] {
                        user,
                        clave,
                        codPro}, this.mCatalogoOperationCompleted, userState);
        }
        
        private void OnmCatalogoOperationCompleted(object arg) {
            if ((this.mCatalogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mCatalogoCompleted(this, new mCatalogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mFacturaXML3", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mFacturaXML3(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mFacturaXML3", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mFacturaXML3Async(string user, string clave, string pXMLFactura) {
            this.mFacturaXML3Async(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mFacturaXML3Async(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mFacturaXML3OperationCompleted == null)) {
                this.mFacturaXML3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnmFacturaXML3OperationCompleted);
            }
            this.InvokeAsync("mFacturaXML3", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mFacturaXML3OperationCompleted, userState);
        }
        
        private void OnmFacturaXML3OperationCompleted(object arg) {
            if ((this.mFacturaXML3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mFacturaXML3Completed(this, new mFacturaXML3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mNotaDebitoCAE", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mNotaDebitoCAE(string user, string clave, string pXMLDebito) {
            object[] results = this.Invoke("mNotaDebitoCAE", new object[] {
                        user,
                        clave,
                        pXMLDebito});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mNotaDebitoCAEAsync(string user, string clave, string pXMLDebito) {
            this.mNotaDebitoCAEAsync(user, clave, pXMLDebito, null);
        }
        
        /// <remarks/>
        public void mNotaDebitoCAEAsync(string user, string clave, string pXMLDebito, object userState) {
            if ((this.mNotaDebitoCAEOperationCompleted == null)) {
                this.mNotaDebitoCAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmNotaDebitoCAEOperationCompleted);
            }
            this.InvokeAsync("mNotaDebitoCAE", new object[] {
                        user,
                        clave,
                        pXMLDebito}, this.mNotaDebitoCAEOperationCompleted, userState);
        }
        
        private void OnmNotaDebitoCAEOperationCompleted(object arg) {
            if ((this.mNotaDebitoCAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mNotaDebitoCAECompleted(this, new mNotaDebitoCAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mNotaCreditoCAE", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mNotaCreditoCAE(string user, string clave, string pXMLCredito) {
            object[] results = this.Invoke("mNotaCreditoCAE", new object[] {
                        user,
                        clave,
                        pXMLCredito});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mNotaCreditoCAEAsync(string user, string clave, string pXMLCredito) {
            this.mNotaCreditoCAEAsync(user, clave, pXMLCredito, null);
        }
        
        /// <remarks/>
        public void mNotaCreditoCAEAsync(string user, string clave, string pXMLCredito, object userState) {
            if ((this.mNotaCreditoCAEOperationCompleted == null)) {
                this.mNotaCreditoCAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmNotaCreditoCAEOperationCompleted);
            }
            this.InvokeAsync("mNotaCreditoCAE", new object[] {
                        user,
                        clave,
                        pXMLCredito}, this.mNotaCreditoCAEOperationCompleted, userState);
        }
        
        private void OnmNotaCreditoCAEOperationCompleted(object arg) {
            if ((this.mNotaCreditoCAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mNotaCreditoCAECompleted(this, new mNotaCreditoCAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mReciboCaja", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mReciboCaja(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mReciboCaja", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mReciboCajaAsync(string user, string clave, string pXMLFactura) {
            this.mReciboCajaAsync(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mReciboCajaAsync(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mReciboCajaOperationCompleted == null)) {
                this.mReciboCajaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmReciboCajaOperationCompleted);
            }
            this.InvokeAsync("mReciboCaja", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mReciboCajaOperationCompleted, userState);
        }
        
        private void OnmReciboCajaOperationCompleted(object arg) {
            if ((this.mReciboCajaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mReciboCajaCompleted(this, new mReciboCajaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mFacturaCAE", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mFacturaCAE(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mFacturaCAE", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mFacturaCAEAsync(string user, string clave, string pXMLFactura) {
            this.mFacturaCAEAsync(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mFacturaCAEAsync(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mFacturaCAEOperationCompleted == null)) {
                this.mFacturaCAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmFacturaCAEOperationCompleted);
            }
            this.InvokeAsync("mFacturaCAE", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mFacturaCAEOperationCompleted, userState);
        }
        
        private void OnmFacturaCAEOperationCompleted(object arg) {
            if ((this.mFacturaCAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mFacturaCAECompleted(this, new mFacturaCAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mFacturaXMLCorreo2", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mFacturaXMLCorreo2(string user, string clave, string pXMLFactura) {
            object[] results = this.Invoke("mFacturaXMLCorreo2", new object[] {
                        user,
                        clave,
                        pXMLFactura});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mFacturaXMLCorreo2Async(string user, string clave, string pXMLFactura) {
            this.mFacturaXMLCorreo2Async(user, clave, pXMLFactura, null);
        }
        
        /// <remarks/>
        public void mFacturaXMLCorreo2Async(string user, string clave, string pXMLFactura, object userState) {
            if ((this.mFacturaXMLCorreo2OperationCompleted == null)) {
                this.mFacturaXMLCorreo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnmFacturaXMLCorreo2OperationCompleted);
            }
            this.InvokeAsync("mFacturaXMLCorreo2", new object[] {
                        user,
                        clave,
                        pXMLFactura}, this.mFacturaXMLCorreo2OperationCompleted, userState);
        }
        
        private void OnmFacturaXMLCorreo2OperationCompleted(object arg) {
            if ((this.mFacturaXMLCorreo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mFacturaXMLCorreo2Completed(this, new mFacturaXMLCorreo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mObtieneInfoCorrelativo", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mObtieneInfoCorrelativo(string user, string clave, string resolucion) {
            object[] results = this.Invoke("mObtieneInfoCorrelativo", new object[] {
                        user,
                        clave,
                        resolucion});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mObtieneInfoCorrelativoAsync(string user, string clave, string resolucion) {
            this.mObtieneInfoCorrelativoAsync(user, clave, resolucion, null);
        }
        
        /// <remarks/>
        public void mObtieneInfoCorrelativoAsync(string user, string clave, string resolucion, object userState) {
            if ((this.mObtieneInfoCorrelativoOperationCompleted == null)) {
                this.mObtieneInfoCorrelativoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmObtieneInfoCorrelativoOperationCompleted);
            }
            this.InvokeAsync("mObtieneInfoCorrelativo", new object[] {
                        user,
                        clave,
                        resolucion}, this.mObtieneInfoCorrelativoOperationCompleted, userState);
        }
        
        private void OnmObtieneInfoCorrelativoOperationCompleted(object arg) {
            if ((this.mObtieneInfoCorrelativoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mObtieneInfoCorrelativoCompleted(this, new mObtieneInfoCorrelativoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eforcon.com/WebService/mConsultarFaceRegimenFel", RequestNamespace="http://www.eforcon.com/WebService", ResponseNamespace="http://www.eforcon.com/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSO_clsResponseGeneral mConsultarFaceRegimenFel(string user, string clave, string resolucion, string numero) {
            object[] results = this.Invoke("mConsultarFaceRegimenFel", new object[] {
                        user,
                        clave,
                        resolucion,
                        numero});
            return ((SSO_clsResponseGeneral)(results[0]));
        }
        
        /// <remarks/>
        public void mConsultarFaceRegimenFelAsync(string user, string clave, string resolucion, string numero) {
            this.mConsultarFaceRegimenFelAsync(user, clave, resolucion, numero, null);
        }
        
        /// <remarks/>
        public void mConsultarFaceRegimenFelAsync(string user, string clave, string resolucion, string numero, object userState) {
            if ((this.mConsultarFaceRegimenFelOperationCompleted == null)) {
                this.mConsultarFaceRegimenFelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmConsultarFaceRegimenFelOperationCompleted);
            }
            this.InvokeAsync("mConsultarFaceRegimenFel", new object[] {
                        user,
                        clave,
                        resolucion,
                        numero}, this.mConsultarFaceRegimenFelOperationCompleted, userState);
        }
        
        private void OnmConsultarFaceRegimenFelOperationCompleted(object arg) {
            if ((this.mConsultarFaceRegimenFelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mConsultarFaceRegimenFelCompleted(this, new mConsultarFaceRegimenFelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eforcon.com/WebService")]
    public partial class SSO_clsResponseGeneral {
        
        private bool pResultadoField;
        
        private string pDescripcionField;
        
        private string pCAEField;
        
        private string pIdSatField;
        
        private string pCAECField;
        
        private string pIdSerieField;
        
        private string pResolucionField;
        
        private string pDocumentoInicioField;
        
        private string pDocumentoFinField;
        
        private string pFechaResolucionField;
        
        private string pDocumentoSiguienteField;
        
        private string pNitField;
        
        private string pRazonSocialField;
        
        private string pDireccionField;
        
        private string pDescripcionEmpField;
        
        private string pTipoDocumentoField;
        
        private string pRutaField;
        
        private string pDesProdField;
        
        private string pPrecioField;
        
        private string pFechaEmisionField;
        
        /// <remarks/>
        public bool pResultado {
            get {
                return this.pResultadoField;
            }
            set {
                this.pResultadoField = value;
            }
        }
        
        /// <remarks/>
        public string pDescripcion {
            get {
                return this.pDescripcionField;
            }
            set {
                this.pDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public string pCAE {
            get {
                return this.pCAEField;
            }
            set {
                this.pCAEField = value;
            }
        }
        
        /// <remarks/>
        public string pIdSat {
            get {
                return this.pIdSatField;
            }
            set {
                this.pIdSatField = value;
            }
        }
        
        /// <remarks/>
        public string pCAEC {
            get {
                return this.pCAECField;
            }
            set {
                this.pCAECField = value;
            }
        }
        
        /// <remarks/>
        public string pIdSerie {
            get {
                return this.pIdSerieField;
            }
            set {
                this.pIdSerieField = value;
            }
        }
        
        /// <remarks/>
        public string pResolucion {
            get {
                return this.pResolucionField;
            }
            set {
                this.pResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string pDocumentoInicio {
            get {
                return this.pDocumentoInicioField;
            }
            set {
                this.pDocumentoInicioField = value;
            }
        }
        
        /// <remarks/>
        public string pDocumentoFin {
            get {
                return this.pDocumentoFinField;
            }
            set {
                this.pDocumentoFinField = value;
            }
        }
        
        /// <remarks/>
        public string pFechaResolucion {
            get {
                return this.pFechaResolucionField;
            }
            set {
                this.pFechaResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string pDocumentoSiguiente {
            get {
                return this.pDocumentoSiguienteField;
            }
            set {
                this.pDocumentoSiguienteField = value;
            }
        }
        
        /// <remarks/>
        public string pNit {
            get {
                return this.pNitField;
            }
            set {
                this.pNitField = value;
            }
        }
        
        /// <remarks/>
        public string pRazonSocial {
            get {
                return this.pRazonSocialField;
            }
            set {
                this.pRazonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string pDireccion {
            get {
                return this.pDireccionField;
            }
            set {
                this.pDireccionField = value;
            }
        }
        
        /// <remarks/>
        public string pDescripcionEmp {
            get {
                return this.pDescripcionEmpField;
            }
            set {
                this.pDescripcionEmpField = value;
            }
        }
        
        /// <remarks/>
        public string pTipoDocumento {
            get {
                return this.pTipoDocumentoField;
            }
            set {
                this.pTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string pRuta {
            get {
                return this.pRutaField;
            }
            set {
                this.pRutaField = value;
            }
        }
        
        /// <remarks/>
        public string pDesProd {
            get {
                return this.pDesProdField;
            }
            set {
                this.pDesProdField = value;
            }
        }
        
        /// <remarks/>
        public string pPrecio {
            get {
                return this.pPrecioField;
            }
            set {
                this.pPrecioField = value;
            }
        }
        
        /// <remarks/>
        public string pFechaEmision {
            get {
                return this.pFechaEmisionField;
            }
            set {
                this.pFechaEmisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mLoginCompletedEventHandler(object sender, mLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mFacturaXMLCompletedEventHandler(object sender, mFacturaXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mFacturaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mFacturaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mNotaCreditoXmlCompletedEventHandler(object sender, mNotaCreditoXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mNotaCreditoXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mNotaCreditoXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mNotaDebitoXmlCompletedEventHandler(object sender, mNotaDebitoXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mNotaDebitoXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mNotaDebitoXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mFacturaCopiaXMLCompletedEventHandler(object sender, mFacturaCopiaXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mFacturaCopiaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mFacturaCopiaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mNotaCreditoCopiaXmlCompletedEventHandler(object sender, mNotaCreditoCopiaXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mNotaCreditoCopiaXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mNotaCreditoCopiaXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mNotaDebitoCopiaXmlCompletedEventHandler(object sender, mNotaDebitoCopiaXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mNotaDebitoCopiaXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mNotaDebitoCopiaXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mAnularFacturaCompletedEventHandler(object sender, mAnularFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mAnularFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mAnularFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mAnularNCCompletedEventHandler(object sender, mAnularNCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mAnularNCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mAnularNCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mAnularNDCompletedEventHandler(object sender, mAnularNDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mAnularNDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mAnularNDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mObtieneInfoFACECompletedEventHandler(object sender, mObtieneInfoFACECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mObtieneInfoFACECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mObtieneInfoFACECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mObtieneInfoNCECompletedEventHandler(object sender, mObtieneInfoNCECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mObtieneInfoNCECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mObtieneInfoNCECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mObtieneInfoNDECompletedEventHandler(object sender, mObtieneInfoNDECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mObtieneInfoNDECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mObtieneInfoNDECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mCrearEmpresaCompletedEventHandler(object sender, mCrearEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mCrearEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mCrearEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mFacturaXML2CompletedEventHandler(object sender, mFacturaXML2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mFacturaXML2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mFacturaXML2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mCatalogoCompletedEventHandler(object sender, mCatalogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mCatalogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mCatalogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mFacturaXML3CompletedEventHandler(object sender, mFacturaXML3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mFacturaXML3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mFacturaXML3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mNotaDebitoCAECompletedEventHandler(object sender, mNotaDebitoCAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mNotaDebitoCAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mNotaDebitoCAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mNotaCreditoCAECompletedEventHandler(object sender, mNotaCreditoCAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mNotaCreditoCAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mNotaCreditoCAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mReciboCajaCompletedEventHandler(object sender, mReciboCajaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mReciboCajaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mReciboCajaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mFacturaCAECompletedEventHandler(object sender, mFacturaCAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mFacturaCAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mFacturaCAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mFacturaXMLCorreo2CompletedEventHandler(object sender, mFacturaXMLCorreo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mFacturaXMLCorreo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mFacturaXMLCorreo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mObtieneInfoCorrelativoCompletedEventHandler(object sender, mObtieneInfoCorrelativoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mObtieneInfoCorrelativoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mObtieneInfoCorrelativoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void mConsultarFaceRegimenFelCompletedEventHandler(object sender, mConsultarFaceRegimenFelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mConsultarFaceRegimenFelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mConsultarFaceRegimenFelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSO_clsResponseGeneral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSO_clsResponseGeneral)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591